name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  quality-control:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.3"
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: List Installed Dependencies
        run: composer show -D
      - name: Execute command
        run: composer qc

  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: "secret"
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: "laravel"
          MYSQL_USER: "laravel"
          MYSQL_PASSWORD: "secret"
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.3"
          coverage: xdebug
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: List Installed Dependencies
        run: composer show -D
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Execute tests (Unit and Feature tests) via PestPHP
        run: XDEBUG_MODE=coverage ./vendor/bin/pest --coverage --coverage-clover clover.xml
      - name: Make code coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          coverage_badge_path: output/code-coverage.svg
          push_badge: false
      - name: Git push to image-data branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output
          publish_branch: image-data
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
